/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.component.HeaderRenderer;
import com.claim.controller.LogAppController;
import com.claim.object.ObjLogApplication;
import com.claim.support.CssStyle;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poolsawat
 */
public class UiHistoryVersion extends javax.swing.JInternalFrame {
    private DefaultTableModel tableModel;
    /**
     * Creates new form UiHistoryVersion
     */
    public UiHistoryVersion() {
        initComponents();
        tableModel = (DefaultTableModel)tableHistoryVersion.getModel();
        loadTable();
    }
    private void loadTable() {
        ((DefaultTableModel) tableHistoryVersion.getModel()).setRowCount(0);
        List<ObjLogApplication> listLog = new LogAppController().getListHistoryVersion();
        for (int i = 0; i < listLog.size(); i++) {
            ObjLogApplication objLog = listLog.get(i);
            Vector data = new Vector();
            data.add(objLog.getLog_name());
            data.add(objLog.getLog_desc());            
            data.add(objLog.getLog_createdate());
            data.add(objLog.getLog_status_desc());
            tableModel.addRow(data);
            tableHistoryVersion.setRowHeight(i, 30);            
        }
        tableHistoryVersion.setModel(tableModel);

        new HeaderRenderer().setWidthAsPercentages(tableHistoryVersion, 0.07, 0.68, 0.15, 0.10);
        ((DefaultTableCellRenderer) tableHistoryVersion.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistoryVersion = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "แสดงรายการประวัติของเวอชั่นโปรแกรม", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        tableHistoryVersion.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        tableHistoryVersion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "version", "รายละเอียด", "วันที่ปรับเวอชั่น", "โดย"
            }
        ));
        jScrollPane1.setViewportView(tableHistoryVersion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHistoryVersion;
    // End of variables declaration//GEN-END:variables
}
