/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.controller.CreateDataStoreController;
import com.claim.controller.LogAppController;
import com.claim.dao.UtilDao;
import com.claim.object.ObjCallStoreCreateData;
import com.claim.support.FunctionUtil;
import com.claim.support.Console;
import com.claim.constants.ConstantMessage;
import com.claim.constants.ConstantVariable;
import com.claim.support.NetUtils;
import com.claim.support.Picker;
import com.claim.object.ProgrameStatus;
import com.claim.dialog.DialogWaitProcess;
import com.claim.support.DateUtil;
import com.claim.support.NumberUtil;
import java.awt.event.ItemEvent;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Poolsawat.a
 */
public class UiCreateData extends javax.swing.JInternalFrame {

    private CreateDataStoreController createStoreController;
    boolean staCheck = false;

    /**
     * Creates new form UiCreateData
     */
    public UiCreateData() {
        initComponents();
        this.createStoreController = new CreateDataStoreController();
        this.loadComboCreateData();
        this.loadTextBoxDate();
    }

    private void loadTextBoxDate() {
        txt_opdStart.setText(DateUtil.DATE_DEFAULT);
        //txt_sendStart.setText("20141001");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rGroupIndv_late = new javax.swing.ButtonGroup();
        rGroupOpae74_Option = new javax.swing.ButtonGroup();
        rGroup_Process = new javax.swing.ButtonGroup();
        rGroupRefer_Option = new javax.swing.ButtonGroup();
        jPanel37 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboCreateTable = new javax.swing.JComboBox();
        lb_error1 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        radio_option_74 = new javax.swing.JRadioButton();
        radio_option_all = new javax.swing.JRadioButton();
        radio_option_opae = new javax.swing.JRadioButton();
        lb_error11 = new javax.swing.JLabel();
        jPanelOpd = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_opdStart = new javax.swing.JButton();
        btn_opdStop = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_opdStart = new javax.swing.JTextField();
        txt_opdStop = new javax.swing.JTextField();
        lb_error2 = new javax.swing.JLabel();
        lb_error3 = new javax.swing.JLabel();
        jPanelSend = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_sendStart = new javax.swing.JButton();
        btn_sendStop = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_sendStart = new javax.swing.JTextField();
        txt_sendStop = new javax.swing.JTextField();
        lb_error4 = new javax.swing.JLabel();
        lb_error5 = new javax.swing.JLabel();
        rGroupOpae74_process = new javax.swing.JPanel();
        radio_process_default = new javax.swing.JRadioButton();
        radio_process_finish = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        comboStmpNoRound = new javax.swing.JComboBox();
        lb_error7 = new javax.swing.JLabel();
        comboStmpNoYear = new javax.swing.JComboBox();
        comboStmpNoMonth = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_error8 = new javax.swing.JLabel();
        lb_error9 = new javax.swing.JLabel();
        txt_stmp_no = new javax.swing.JComboBox();
        jPanel45 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        lb_error12 = new javax.swing.JLabel();
        txt_pay_rate = new javax.swing.JTextField();
        jPanel36 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        radio_indv_in_time = new javax.swing.JRadioButton();
        radio_indv_late_time = new javax.swing.JRadioButton();
        lb_error13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radio_refer_spliteYear = new javax.swing.JRadioButton();
        radio_refer_allYear = new javax.swing.JRadioButton();
        lb_errorReferOption = new javax.swing.JLabel();
        btnCreateData = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("หน้าจสร้างข้อมูล");
        setAutoscrolls(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Excel-icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1250, 550));

        jPanel37.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ประเภทบริการ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel1.setText("ชื่อตาราง: ");

        comboCreateTable.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N

        lb_error1.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error1.setForeground(new java.awt.Color(255, 0, 51));
        lb_error1.setText("*");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_error1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCreateTable, 0, 336, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCreateTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lb_error1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel39.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pay Rate [กรณี สร้างข้อมูล OPAE+74]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24), java.awt.Color.orange)); // NOI18N

        rGroupOpae74_Option.add(radio_option_74);
        radio_option_74.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_option_74.setText("74");

        rGroupOpae74_Option.add(radio_option_all);
        radio_option_all.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_option_all.setText("OPAE+74");

        rGroupOpae74_Option.add(radio_option_opae);
        radio_option_opae.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_option_opae.setText("OPAE");

        lb_error11.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error11.setForeground(new java.awt.Color(255, 0, 51));
        lb_error11.setText("*");

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radio_option_all, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radio_option_opae)
                .addGap(18, 18, 18)
                .addComponent(radio_option_74)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lb_error11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_option_all)
                    .addComponent(radio_option_74)
                    .addComponent(radio_option_opae))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOpd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "วันรับบริการ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel3.setText("ตั้งแต่:");

        btn_opdStart.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_opdStart.setText("เลือก");
        btn_opdStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opdStartMouseClicked(evt);
            }
        });

        btn_opdStop.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_opdStop.setText("เลือก");
        btn_opdStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_opdStopMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel14.setText("ถึง: ");

        txt_opdStart.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_opdStart.setEnabled(false);

        txt_opdStop.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_opdStop.setEnabled(false);

        lb_error2.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error2.setForeground(new java.awt.Color(255, 0, 51));
        lb_error2.setText("*");

        lb_error3.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error3.setForeground(new java.awt.Color(255, 0, 51));
        lb_error3.setText("*");

        javax.swing.GroupLayout jPanelOpdLayout = new javax.swing.GroupLayout(jPanelOpd);
        jPanelOpd.setLayout(jPanelOpdLayout);
        jPanelOpdLayout.setHorizontalGroup(
            jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpdLayout.createSequentialGroup()
                .addGroup(jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpdLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_opdStart, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_opdStart))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpdLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lb_error2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpdLayout.createSequentialGroup()
                        .addComponent(txt_opdStop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_opdStop))
                    .addComponent(lb_error3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOpdLayout.setVerticalGroup(
            jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txt_opdStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_opdStop))
                    .addGroup(jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_opdStart)
                        .addComponent(txt_opdStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOpdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_error2)
                    .addComponent(lb_error3)))
        );

        jPanelSend.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "วันที่ส่งข้อมูล", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N
        jPanelSend.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel15.setText("ตั้งแต่: ");

        btn_sendStart.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_sendStart.setText("เลือก");
        btn_sendStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendStartMouseClicked(evt);
            }
        });

        btn_sendStop.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_sendStop.setText("เลือก");
        btn_sendStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendStopMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel16.setText("ถึง: ");

        txt_sendStart.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_sendStart.setEnabled(false);

        txt_sendStop.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_sendStop.setEnabled(false);

        lb_error4.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error4.setForeground(new java.awt.Color(255, 0, 51));
        lb_error4.setText("*");

        lb_error5.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error5.setForeground(new java.awt.Color(255, 0, 51));
        lb_error5.setText("*");

        javax.swing.GroupLayout jPanelSendLayout = new javax.swing.GroupLayout(jPanelSend);
        jPanelSend.setLayout(jPanelSendLayout);
        jPanelSendLayout.setHorizontalGroup(
            jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSendLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSendLayout.createSequentialGroup()
                        .addComponent(txt_sendStart, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sendStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(lb_error4))
                .addGap(18, 18, 18)
                .addGroup(jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSendLayout.createSequentialGroup()
                        .addComponent(txt_sendStop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_sendStop))
                    .addComponent(lb_error5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSendLayout.setVerticalGroup(
            jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSendLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sendStart)
                    .addComponent(btn_sendStop)
                    .addComponent(jLabel16)
                    .addComponent(txt_sendStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sendStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_error5)
                    .addComponent(lb_error4))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        rGroupOpae74_process.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "กำหนดงวดการจ่ายเงิน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        rGroup_Process.add(radio_process_default);
        radio_process_default.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        radio_process_default.setSelected(true);
        radio_process_default.setText("สร้างงวดการออกรายงาน ปกติ");
        radio_process_default.setEnabled(false);

        rGroup_Process.add(radio_process_finish);
        radio_process_finish.setFont(new java.awt.Font("TH SarabunPSK", 1, 22)); // NOI18N
        radio_process_finish.setText("สร้างงวดการออกรายงาน ปลายปีงบ (ให้เลือก รอบ = 0)");
        radio_process_finish.setEnabled(false);

        comboStmpNoRound.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        comboStmpNoRound.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboStmpNoRoundItemStateChanged(evt);
            }
        });

        lb_error7.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error7.setForeground(new java.awt.Color(255, 0, 51));
        lb_error7.setText("*");

        comboStmpNoYear.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N

        comboStmpNoMonth.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        comboStmpNoMonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboStmpNoMonthItemStateChanged(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel37.setText("งวดที่หรือครั้งที่: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("-");

        lb_error8.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error8.setForeground(new java.awt.Color(255, 0, 51));
        lb_error8.setText("*");

        lb_error9.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error9.setForeground(new java.awt.Color(255, 0, 51));
        lb_error9.setText("*");

        txt_stmp_no.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_stmp_no.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboStmpNoYear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboStmpNoMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_error8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboStmpNoRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_stmp_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_error7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lb_error9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboStmpNoRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStmpNoYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStmpNoMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(jLabel4)))
                    .addComponent(txt_stmp_no))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_error8)
                    .addComponent(lb_error9)
                    .addComponent(lb_error7))
                .addContainerGap())
        );

        javax.swing.GroupLayout rGroupOpae74_processLayout = new javax.swing.GroupLayout(rGroupOpae74_process);
        rGroupOpae74_process.setLayout(rGroupOpae74_processLayout);
        rGroupOpae74_processLayout.setHorizontalGroup(
            rGroupOpae74_processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rGroupOpae74_processLayout.createSequentialGroup()
                .addGroup(rGroupOpae74_processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rGroupOpae74_processLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(rGroupOpae74_processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radio_process_default)
                            .addComponent(radio_process_finish)))
                    .addGroup(rGroupOpae74_processLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rGroupOpae74_processLayout.setVerticalGroup(
            rGroupOpae74_processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rGroupOpae74_processLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radio_process_default)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radio_process_finish)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel45.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pay Rate [กรณี สร้างข้อมูล OPAE+74]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24), java.awt.Color.orange)); // NOI18N

        jLabel39.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel39.setText("xxx.xx");

        lb_error12.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error12.setForeground(new java.awt.Color(255, 0, 51));

        txt_pay_rate.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel45Layout.createSequentialGroup()
                        .addComponent(txt_pay_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel39)
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel45Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txt_pay_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_error12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel36.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "รูปแบบการส่งข้อมูล [INDIVIDUAL]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24), new java.awt.Color(0, 153, 0))); // NOI18N
        jPanel36.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N

        jLabel40.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel40.setText("indv_late : ");

        rGroupIndv_late.add(radio_indv_in_time);
        radio_indv_in_time.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_indv_in_time.setText("ทันเวลา");
        radio_indv_in_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_indv_in_timeActionPerformed(evt);
            }
        });

        rGroupIndv_late.add(radio_indv_late_time);
        radio_indv_late_time.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_indv_late_time.setText("ไม่ทันเวลา");
        radio_indv_late_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_indv_late_timeActionPerformed(evt);
            }
        });

        lb_error13.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_error13.setForeground(new java.awt.Color(255, 0, 51));
        lb_error13.setText("*");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(radio_indv_in_time)
                        .addGap(18, 18, 18)
                        .addComponent(radio_indv_late_time)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(radio_indv_in_time, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_indv_late_time, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "สำหรับ [OPREFER]", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24), new java.awt.Color(102, 51, 255))); // NOI18N

        radio_refer_spliteYear.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_refer_spliteYear.setText("ไม่กวาดข้อมูล แยกปี");

        radio_refer_allYear.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radio_refer_allYear.setText("กวาดข้อมูล รวมทุกปี");

        lb_errorReferOption.setFont(new java.awt.Font("TH SarabunPSK", 1, 14)); // NOI18N
        lb_errorReferOption.setForeground(java.awt.Color.red);
        lb_errorReferOption.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_errorReferOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radio_refer_spliteYear)
                        .addGap(18, 18, 18)
                        .addComponent(radio_refer_allYear)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_refer_spliteYear)
                    .addComponent(radio_refer_allYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_errorReferOption)
                .addContainerGap())
        );

        btnCreateData.setBackground(new java.awt.Color(153, 255, 153));
        btnCreateData.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btnCreateData.setForeground(new java.awt.Color(51, 51, 255));
        btnCreateData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/progressbar.png"))); // NOI18N
        btnCreateData.setText("เริ่มประมวลผล...");
        btnCreateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rGroupOpae74_process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOpd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCreateData, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOpd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreateData, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addComponent(rGroupOpae74_process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opdStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opdStartMouseClicked
        HashMap mapParam = new HashMap();
        mapParam.put("btn", btn_opdStart);
        mapParam.put("txt", txt_opdStart);
        mapParam.put("panel", jPanelOpd);
        mapParam.put("formatDate", DateUtil.DATE_FORMAT);
        new Picker().PickerJInternal(this, mapParam);
    }//GEN-LAST:event_btn_opdStartMouseClicked

    private void btn_opdStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_opdStopMouseClicked
        HashMap mapParam = new HashMap();
        mapParam.put("btn", btn_opdStop);
        mapParam.put("txt", txt_opdStop);
        mapParam.put("panel", jPanelOpd);
        mapParam.put("formatDate", DateUtil.DATE_FORMAT);
        new Picker().PickerJInternal(this, mapParam);
    }//GEN-LAST:event_btn_opdStopMouseClicked

    private void btn_sendStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendStartMouseClicked
        HashMap mapParam = new HashMap();
        mapParam.put("btn", btn_sendStart);
        mapParam.put("txt", txt_sendStart);
        mapParam.put("panel", jPanelSend);
        mapParam.put("formatDate", DateUtil.DATE_FORMAT);
        new Picker().PickerJInternal(this, mapParam);
    }//GEN-LAST:event_btn_sendStartMouseClicked

    private void btn_sendStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendStopMouseClicked
        HashMap mapParam = new HashMap();
        mapParam.put("btn", btn_sendStop);
        mapParam.put("txt", txt_sendStop);
        mapParam.put("panel", jPanelSend);
        mapParam.put("formatDate", DateUtil.DATE_FORMAT);
        new Picker().PickerJInternal(this, mapParam);
    }//GEN-LAST:event_btn_sendStopMouseClicked

    private void comboStmpNoRoundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboStmpNoRoundItemStateChanged
        //        if (evt.getStateChange() == ItemEvent.SELECTED && comboRound.getSelectedIndex() != 0 && !txt_stmp.getText().isEmpty()) {
        //            txt_stmp.setText(txt_stmp.getText().substring(0, 6) + "-" + comboRound.getSelectedItem());
        //        }
        /*String stmp_ = comboYearNo.getSelectedItem() + "" + comboMonthNo.getSelectedItem()+
         "-"+String.valueOf(comboRound.getSelectedIndex());
         checkCreateData_dateopd(stmp_, listPaySta_Indi);*/
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (comboStmpNoRound.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(UiCreateData.this,
                        "ถ้าเลือกรอบ = 0 แสดงว่าท่านกำลังจะออก รายงานสรุป ปลายปีงบ : " + comboStmpNoYear.getSelectedItem(),
                        "ข้อความเตือนการสร้างข้อมูล", JOptionPane.INFORMATION_MESSAGE);
                radio_process_finish.setSelected(true);
                radio_process_default.setSelected(false);
            } else {
                radio_process_default.setSelected(true);
                radio_process_finish.setSelected(false);
            }
        }
    }//GEN-LAST:event_comboStmpNoRoundItemStateChanged

    private void comboStmpNoMonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboStmpNoMonthItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int[] round = new int[21];
            if (comboStmpNoMonth.getSelectedIndex() > 0) {
                for (int i = 0; i < round.length; i++) {
                    comboStmpNoRound.addItem(i);
                }
            }
        }
    }//GEN-LAST:event_comboStmpNoMonthItemStateChanged

    private void radio_indv_in_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_indv_in_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_indv_in_timeActionPerformed

    private void radio_indv_late_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_indv_late_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_indv_late_timeActionPerformed

    private void btnCreateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDataActionPerformed
        final DialogWaitProcess f = new DialogWaitProcess();
        if (checkFormCreateData().isEmpty()) {

            final DialogWaitProcess frmCheck = new DialogWaitProcess();
            frmCheck.setVisible(true);
            frmCheck.setTitle("กำลังตรวจสอบ งวด stmp กรุณารอ...");

            Thread threadCheck = new Thread(new Runnable() {
                @Override
                public void run() {
                    int indexTable = comboCreateTable.getSelectedIndex();
                    String stmp = comboStmpNoYear.getSelectedItem() + "" + comboStmpNoMonth.getSelectedItem()
                            + "-" + String.valueOf(comboStmpNoRound.getSelectedIndex());
                    staCheck = createStoreController.checkCreateDataDupicate(setInputFormCreateData());
                    frmCheck.setVisible(false);

                    if (!staCheck) { // false = ไม่ซ้ำ
                        int selectOption = JOptionPane.showConfirmDialog(null,
                                "ยืนยันการประมวลผลโปรแกรม",
                                "Processing...", JOptionPane.YES_NO_OPTION);
                        if (selectOption == JOptionPane.YES_OPTION) {
                            try {
                                f.setVisible(true);

                                Thread thread = new Thread(new Runnable() {
                                    @Override
                                    public void run() {
                                        ProgrameStatus programeStatus = new ProgrameStatus();
                                        try {
                                            if (programeStatus.getProcessStatus()) {
                                                programeStatus = createStoreController.startRunStore(setInputFormCreateData());
                                                Console.LOG(" ผลของทางโปรแกรม: " + programeStatus.getMessage(), 1);
                                                Console.LOG(" ผลของฐานข้อมูล: " + createStoreController.getLogReport(comboCreateTable.getSelectedIndex()), 1);
                                                f.setVisible(false);
                                            } else {
                                                programeStatus = createStoreController.startRunStore(setInputFormCreateData());
                                                Console.LOG(" ผลของทางโปรแกรม: " + programeStatus.getMessage(), 1);
                                                Console.LOG(" ผลของฐานข้อมูล: " + createStoreController.getLogReport(comboCreateTable.getSelectedIndex()), 1);
                                                f.setVisible(false);
                                            }

                                        } catch (SQLException e) {
                                            e.printStackTrace();
                                        }
                                    }
                                });
                                thread.start();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }

                    } else { // true = ซ้ำ
                        Console.LOG(" งวดการสร้างข้อมูลนี้ เคยทำการ ประมวลผลไปแล้ว", 0);
                        Console.LOG(" เงื่อนไข => จะประมวลผล ซ้ำ งวดเดิม ใช่ หรือ ไม่", 0);
                        /* JOptionPane.showMessageDialog(MainBkkTabReport.this,
                         "งวดการจ่ายเงินนี้ ได้ผ่านแจ้งสถานะการจ่ายเงินแล้ว",
                         "ไม่สามารถสร้างข้อมูล งวดการจ่ายเงินนี้ได้",
                         JOptionPane.ERROR_MESSAGE); */

                        int selectOption = JOptionPane.showConfirmDialog(null,
                                "งวดการจ่ายเงินนี้ ได้ผ่านการประมวลผล ไปแล้ว",
                                "ท่านจะ สร้างข้อมูลงวดนี้ ซ้ำ ใช่หรือไม่", JOptionPane.YES_NO_OPTION);
                        if (selectOption == JOptionPane.YES_OPTION) {
                            try {
                                f.setVisible(true);

                                Thread thread = new Thread(new Runnable() {
                                    @Override
                                    public void run() {
                                        ProgrameStatus programeStatus = new ProgrameStatus();
                                        try {
                                            if (programeStatus.getProcessStatus()) {
                                                programeStatus = createStoreController.startRunStore(setInputFormCreateData());
                                                Console.LOG(" ผลของทางโปรแกรม " + programeStatus.getMessage(), 1);
                                                Console.LOG(" ผลของฐานข้อมูล " + createStoreController.getLogReport(comboCreateTable.getSelectedIndex()), 1);
                                                f.setVisible(false);
                                            } else {
                                                programeStatus = createStoreController.startRunStore(setInputFormCreateData());
                                                Console.LOG(" ผลของทางโปรแกรม " + programeStatus.getMessage(), 1);
                                                Console.LOG(" ผลของฐานข้อมูล " + createStoreController.getLogReport(comboCreateTable.getSelectedIndex()), 1);
                                                f.setVisible(false);
                                            }

                                        } catch (SQLException e) {
                                            e.printStackTrace();
                                            Console.LOG(e.getMessage(), 0);
                                        }
                                    }
                                });
                                thread.start();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                    String desc = " ทำการสร้างข้อมูล " + ConstantVariable.PROCE_CREATE_TABLE[comboCreateTable.getSelectedIndex()];
                    desc += " โดยมาค่าที่ ส่งเข้าไปคือ [ " + setInputFormCreateData().toString() + " ]";
                    new LogAppController().createLog("ทำการสร้างข้อมูล " + ConstantVariable.PROCE_CREATE_TABLE[comboCreateTable.getSelectedIndex()], desc, NetUtils.getIpAddress(), 1);
                }
            });
            threadCheck.start();
        } else {
            JOptionPane.showMessageDialog(this,
                    ConstantMessage.MSG_ENTER_DATA,
                    ConstantMessage.MSG_ENTER_DATA,
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateDataActionPerformed

    private ObjCallStoreCreateData setInputFormCreateData() {
        ObjCallStoreCreateData objData = new ObjCallStoreCreateData();
        objData.setIndex_table(comboCreateTable.getSelectedIndex());
        objData.setOpd_date_start(new DateUtil().changeDateFormat(txt_opdStart.getText(), DateUtil.DATE_FORMAT, DateUtil.DATE_FORMAT_TO));
        objData.setOpd_date_stop(new DateUtil().changeDateFormat(txt_opdStop.getText(), DateUtil.DATE_FORMAT, DateUtil.DATE_FORMAT_TO));
        objData.setOpd_send_start(new DateUtil().changeDateFormat(txt_sendStart.getText(), DateUtil.DATE_FORMAT, DateUtil.DATE_FORMAT_TO));
        objData.setOpd_send_stop(new DateUtil().changeDateFormat(txt_sendStop.getText(), DateUtil.DATE_FORMAT, DateUtil.DATE_FORMAT_TO));
        objData.setStmp(comboStmpNoYear.getSelectedItem() + "" + comboStmpNoMonth.getSelectedItem());
        objData.setStmp_round(String.valueOf(comboStmpNoRound.getSelectedIndex()));
        objData.setStmp_no(String.valueOf(txt_stmp_no.getSelectedItem()));
        objData.setPay_rate(txt_pay_rate.getText());

        objData.setStmpyyyymm_no(comboStmpNoYear.getSelectedItem() + "" + comboStmpNoMonth.getSelectedItem() + "-" + String.valueOf(comboStmpNoRound.getSelectedIndex()));
        objData.setStmpyyyymmno((comboStmpNoYear.getSelectedItem() + "" + comboStmpNoMonth.getSelectedItem() + "" + String.valueOf(comboStmpNoRound.getSelectedIndex())));

        // for opae 
        if (radio_option_all.isSelected()) {
            objData.setOpae_option(0);
        } else if (radio_option_opae.isSelected()) {
            objData.setOpae_option(1);
        } else if (radio_option_74.isSelected()) {
            objData.setOpae_option(2);
        }
        // for individual
        if (radio_indv_in_time.isSelected()) { // ทันเวลา
            objData.setIndv_late("0");
        } else if (radio_indv_late_time.isSelected()) {  // ไม่ทันเวลา/ล่าช้า
            objData.setIndv_late("1");
        }
        if (radio_process_default.isSelected()) {
            objData.setProcess_create(0);
        } else {
            objData.setProcess_create(1);
        }
        if (radio_refer_allYear.isSelected()) {
            // เรียก package 57 และ 58
            objData.setRefer_option(1);
        } else if (radio_refer_spliteYear.isSelected()) {
            // เรียก package 57 หรือ 58 ตามแต่ dateopd end
            objData.setRefer_option(2);
        } else {
            objData.setRefer_option(0);
        }
        objData.setGroup_report_type(1);
        return objData;
    }

    private void loadComboCreateData() {
        String[] arrTable = ConstantVariable.PROCE_CREATE_TABLE;
        for (String strTable : arrTable) {
            comboCreateTable.addItem(strTable);
        }
        String[] arrMonth = ConstantVariable.INDEX_MONTH;
        for (int i = 0; i < arrMonth.length; i++) {
            comboStmpNoMonth.addItem(arrMonth[i]);
        }
        int[] arrYear = NumberUtil.INDEX_YEAR(3);
        for (int i = 0; i < arrYear.length; i++) {
            comboStmpNoYear.addItem(String.valueOf(arrYear[i]));
        }
        String currentYear = new UtilDao().getCurrentYearFromServer();
        System.out.println("currentYear ::==" + currentYear);
        comboStmpNoYear.setSelectedItem(currentYear);
    }

    private List<Integer> checkFormCreateData() {
        List<Integer> error = new ArrayList<Integer>();
        if (comboCreateTable.getSelectedIndex() == 0) {
            error.add(1);
            lb_error1.setText(ConstantMessage.MSG_SELECT_DATA);
        } else {
            lb_error1.setText("");
        }
        if (txt_opdStart.getText().isEmpty()) {
            error.add(1);
            lb_error2.setText("กรุณาเลือกวัน");
        } else {
            lb_error2.setText("");
        }
        if (txt_opdStop.getText().isEmpty()) {
            error.add(1);
            lb_error3.setText("กรุณาเลือกวัน");
        } else {
            lb_error3.setText("");
        }
        /*if (txt_sendStart.getText().isEmpty()) {
         error.add(1);
         lb_error4.setText("กรุณาเลือกวัน");
         } else {
         lb_error4.setText("");
         }
         if (txt_sendStop.getText().isEmpty()) {
         error.add(1);
         lb_error5.setText("กรุณาเลือกวัน");
         } else {
         lb_error5.setText("");
         }*/
        /*if (comboYearNo.getSelectedIndex() == 0) {
         error.add(1);
         lb_error6.setText("กรุณาเลือกวัน");
         } else {
         lb_error6.setText("");
         }*/

        if (comboStmpNoMonth.getSelectedIndex() == 0) {
            error.add(1);
            lb_error8.setText("กรุณาเลือกเดือน");
        } else {
            lb_error8.setText("");
        }
        if (comboStmpNoRound.getSelectedIndex() == 0) {
            //error.add(1);
            //lb_error7.setText(Constants.MSG_SELECT_NO);
            JOptionPane.showMessageDialog(UiCreateData.this,
                    "ถ้าเลือกรอบ = 0 แสดงว่าท่านกำลังจะออก รายงานสรุป ปลายปีงบ : " + comboStmpNoYear.getSelectedItem(),
                    "ข้อความเตือนการสร้างข้อมูล", JOptionPane.INFORMATION_MESSAGE);
            radio_process_finish.setSelected(true);
            radio_process_default.setSelected(false);
        } else {
            lb_error7.setText("");
            radio_process_default.setSelected(true);
            radio_process_finish.setSelected(false);
        }
//        if (txt_stmp_no.getText().isEmpty()) {
//            error.add(1);
//            lb_error9.setText("กรุณากรอก งวดที่หรือครั้งที่ ของรายงาน");
//        } else {
//            try {
//                Integer.parseInt(txt_stmp_no.getText());
//                System.out.println("An integer");
//                lb_error9.setText("");
//            } catch (NumberFormatException exception) {
//                lb_error9.setText("กรุณากรอก งวดที่หรือครั้งที่ เป็นตัวเลขเท่านั้น");
//            }
//        }

        if (comboCreateTable.getSelectedIndex() == 2) {
            if (radio_option_74.isSelected() || radio_option_all.isSelected() || radio_option_opae.isSelected()) {
                lb_error11.setText("");
            } else {
                error.add(1);
                lb_error11.setText("กรุณาเลือก รูปแบบ การสร้างข้อมูลของ OPAE+74 or OPAE or 74");
            }

            if (txt_pay_rate.getText().isEmpty()) {
                error.add(1);
                lb_error12.setText("กรุณา ใส่ Pay Rate เมื่อ สร้างข้อมูล OPAE");
            } else {
                lb_error12.setText("");
            }
        } else {
            lb_error12.setText("");
            lb_error11.setText("");
        }

        if (comboCreateTable.getSelectedIndex() == 4) { // individual
            if (radio_indv_in_time.isSelected() || radio_indv_late_time.isSelected()) {
                lb_error13.setText("");
            } else {
                error.add(1);
                lb_error13.setText("กรุณาเลือก ประเภทของ การจ่าย Individual จ่ายทัน หรือ จ่ายไม่ทัน ");
            }
        } else {
            lb_error13.setText("");
        }
        if (comboCreateTable.getSelectedIndex() == 5) { // refer
            if (radio_refer_allYear.isSelected() || radio_refer_spliteYear.isSelected()) {
                lb_errorReferOption.setText("");
            } else {
                error.add(1);
                lb_errorReferOption.setText("กรุณาเลือก ประเภทของ กวาดข้อมูลทุกปี(57 และ 58) หรือ แยกปี (57 หรือ 58)");
            }
        } else {
            lb_errorReferOption.setText("");
        }
        return error;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateData;
    private javax.swing.JButton btn_opdStart;
    private javax.swing.JButton btn_opdStop;
    private javax.swing.JButton btn_sendStart;
    private javax.swing.JButton btn_sendStop;
    private javax.swing.JComboBox comboCreateTable;
    private javax.swing.JComboBox comboStmpNoMonth;
    private javax.swing.JComboBox comboStmpNoRound;
    private javax.swing.JComboBox comboStmpNoYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanelOpd;
    private javax.swing.JPanel jPanelSend;
    private javax.swing.JLabel lb_error1;
    private javax.swing.JLabel lb_error11;
    private javax.swing.JLabel lb_error12;
    private javax.swing.JLabel lb_error13;
    private javax.swing.JLabel lb_error2;
    private javax.swing.JLabel lb_error3;
    private javax.swing.JLabel lb_error4;
    private javax.swing.JLabel lb_error5;
    private javax.swing.JLabel lb_error7;
    private javax.swing.JLabel lb_error8;
    private javax.swing.JLabel lb_error9;
    private javax.swing.JLabel lb_errorReferOption;
    private javax.swing.ButtonGroup rGroupIndv_late;
    private javax.swing.ButtonGroup rGroupOpae74_Option;
    private javax.swing.JPanel rGroupOpae74_process;
    private javax.swing.ButtonGroup rGroupRefer_Option;
    private javax.swing.ButtonGroup rGroup_Process;
    private javax.swing.JRadioButton radio_indv_in_time;
    private javax.swing.JRadioButton radio_indv_late_time;
    private javax.swing.JRadioButton radio_option_74;
    private javax.swing.JRadioButton radio_option_all;
    private javax.swing.JRadioButton radio_option_opae;
    private javax.swing.JRadioButton radio_process_default;
    private javax.swing.JRadioButton radio_process_finish;
    private javax.swing.JRadioButton radio_refer_allYear;
    private javax.swing.JRadioButton radio_refer_spliteYear;
    private javax.swing.JTextField txt_opdStart;
    private javax.swing.JTextField txt_opdStop;
    private javax.swing.JTextField txt_pay_rate;
    private javax.swing.JTextField txt_sendStart;
    private javax.swing.JTextField txt_sendStop;
    private javax.swing.JComboBox txt_stmp_no;
    // End of variables declaration//GEN-END:variables
}
