/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.component.HeaderRenderer;
import com.claim.config.ConfigApp;
import com.claim.constants.ConstantMessage;
import com.claim.constants.ConstantFtp;
import com.claim.controller.FileTransferController;
import com.claim.dialog.DialogWaitProcess;
import com.claim.object.ObjFileTransfer;
import com.claim.support.Console;
import com.claim.support.NetUtils;
import com.claim.support.StringOpUtil;
import java.io.File;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author POOL_LAPTOP
 */
public class UiFileTransfer extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiFileTransfer
     */
    DefaultTableModel model = null;
    FileTransferController ftpController = null;
    
    public UiFileTransfer() {
        initComponents();
        ftpController = new FileTransferController();
        model = (DefaultTableModel) table_files_server.getModel();
        loadCombo();
    }
    
    private void loadTableDataModel() {
        List<ObjFileTransfer> ftpList = ftpController.getFileTransfer(ConstantFtp.FTP_RPT_AlIASES[comboReportType.getSelectedIndex()]);
        ((DefaultTableModel) table_files_server.getModel()).setRowCount(0);
        for (int i = 0; i < ftpList.size(); i++) {
            int auto = (i + 1);
            ObjFileTransfer objLog = ftpList.get(i);
            Vector data = new Vector();
            data.add(String.valueOf(auto));
            data.add(objLog.getFtp_name());
            data.add(objLog.getFtp_desc());
            data.add(objLog.getFtp_stmp());
            data.add(objLog.getFtp_createdate());
            data.add(ConstantFtp.FTP_STATUS[objLog.getFtp_status()]);
            model.addRow(data);
            table_files_server.setRowHeight(i, 30);
        }
        table_files_server.setModel(model);
        
        new HeaderRenderer().setWidthAsPercentages(table_files_server, 0.05, 0.20, 0.25, 0.10, 0.20, 0.20);
    }
    
    private void loadCombo() {
        comboReportType.removeAllItems();
        String[] ftpReportType = ConstantFtp.FTP_RPT_LABEL;
        for (String ftpRpt : ftpReportType) {
            comboReportType.addItem(ftpRpt);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboReportType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_remark = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt_location_file = new javax.swing.JTextField();
        btn_chose_file = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_stmp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_lookup_files = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_files_server = new javax.swing.JTable();
        btn_startUplaod = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("อัพโหลดไฟล์ไปยัง server");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1300, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ตั้งค่าการอัพโหลดของรายงาน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        comboReportType.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel1.setText("ประเภทรายงานที่อัพโหลด");

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel2.setText("คำอธิบายการอัพโหลด");

        txt_remark.setColumns(20);
        txt_remark.setRows(5);
        jScrollPane1.setViewportView(txt_remark);

        jLabel3.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel3.setText("เลือก Folder ไฟล์ ที่จะอัพโหลด");

        txt_location_file.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_location_file.setEnabled(false);

        btn_chose_file.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_chose_file.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Search-icon.png"))); // NOI18N
        btn_chose_file.setText("เลือก");
        btn_chose_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chose_fileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel4.setText("งวด / STMP");

        txt_stmp.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboReportType, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_stmp, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_location_file, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_chose_file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_location_file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chose_file)
                    .addComponent(jLabel4)
                    .addComponent(txt_stmp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "งวดไฟล์ที่มีบน server แล้ว", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        btn_lookup_files.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_lookup_files.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Search-icon.png"))); // NOI18N
        btn_lookup_files.setText("ดูไฟล์ บน Server");
        btn_lookup_files.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lookup_filesActionPerformed(evt);
            }
        });

        table_files_server.setAutoCreateRowSorter(true);
        table_files_server.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        table_files_server.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ลำดับ", "ชื่อ", "อธิบาย", "งวด (STMP)", "วันที่อัพโหลด", "สถานะการอัพโหลด"
            }
        ));
        jScrollPane2.setViewportView(table_files_server);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lookup_files, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_lookup_files, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_startUplaod.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btn_startUplaod.setText("เริ่มอัพโหลด");
        btn_startUplaod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startUplaodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_startUplaod, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_startUplaod, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chose_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chose_fileActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Open Folder");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(new File(""));
            int result = fc.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File a = fc.getSelectedFile();
                // Path File method in this class
                String temp = a.getPath();
                txt_location_file.setText(".");
                
                if (temp != null) {
                    txt_location_file.setText(temp);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_chose_fileActionPerformed

    private void btn_lookup_filesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lookup_filesActionPerformed
        if (comboReportType.getSelectedIndex() > 0) {
            loadTableDataModel();
        } else {
            ((DefaultTableModel) table_files_server.getModel()).setRowCount(0);
            Console.LOG(" -- กรุณาเลือก ประเภทรายงานที่จะอัพโหลดก่อน--", 0);
        }
    }//GEN-LAST:event_btn_lookup_filesActionPerformed

    private void btn_startUplaodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startUplaodActionPerformed
        final DialogWaitProcess f = new DialogWaitProcess();
        
        final DialogWaitProcess frmCheck = new DialogWaitProcess();
        frmCheck.setTitle("ระบบกำลังอัพโหลดไป กรุณารอ...");
        
        Thread threadCheck = new Thread(new Runnable() {
            @Override
            public void run() {
                int indexReportType = comboReportType.getSelectedIndex();
                String reportType = comboReportType.getSelectedItem().toString();
                String reportDesc = txt_remark.getText();
                String reportFilePath = txt_location_file.getText();
                String reportStmp = txt_stmp.getText();
                
                System.out.println("indexReportType ::==" + indexReportType);
                System.out.println("reportFilePath ::==" + reportFilePath);
                
                if (indexReportType > 0) {
                    if (!StringOpUtil.removeNull(reportStmp).equals("")) {
                        if (!StringOpUtil.removeNull(reportFilePath).equals("")) {
                            int selectOption = JOptionPane.showConfirmDialog(null,
                                    "เริ่มการอัพโหลดไฟล์ ไปยัง server",
                                    "ท่านจะเริ่มการอัพโหลดไฟล์เดี๋ยวนี้ ใช่หรือไม่", JOptionPane.YES_NO_OPTION);
                            if (selectOption == JOptionPane.YES_OPTION) {
                                frmCheck.setVisible(true);
                                Console.LOG("-- เริ่มการอัพโหลดไฟล์ ไปยัง server --", 1);
                                
                                ObjFileTransfer ftpObj = new ObjFileTransfer();
                                ftpObj.setFtp_name(reportType);
                                ftpObj.setFtp_directory_path(reportFilePath);
                                ftpObj.setFtp_report_type(ConstantFtp.FTP_RPT_AlIASES[indexReportType]);
                                ftpObj.setFtp_report_index(indexReportType);
                                ftpObj.setFtp_stmp(reportStmp);
                                ftpObj.setFtp_desc(reportDesc);
                                ftpObj.setFtp_client_ip(ConfigApp.CURRENT_IP);
                                
                                try {
                                    boolean isUpload = ftpController.uploadMutiFilesWithSFTP(ftpObj);
                                    if (isUpload) {
                                        ftpObj.setFtp_status(1);
                                        Console.LOG("-- upload file ไปยัง server สำเร็จ", 1);
                                    } else {
                                        ftpObj.setFtp_status(0);
                                        Console.LOG("-- ไม่สามารถ upload file ไปยัง server ได้ กรุณาติดต่อเจ้าหน้าที่ดูแลระบบ", 0);
                                    }
                                } catch (Exception e) {
                                    Console.LOG(e.getMessage(), 0);
                                    e.printStackTrace();                                    
                                }
                                
                               // ftpController.createLogFileTransfer(ftpObj);
                                
                                frmCheck.setVisible(false);
                            }
                        } else {
                            JOptionPane.showMessageDialog(UiFileTransfer.this,
                                    ConstantMessage.MSG_FILE_LOCATION_PLEASE,
                                    ConstantMessage.MSG_FILE_LOCATION,
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(UiFileTransfer.this,
                                ConstantMessage.MSG_ENTER_STMP,
                                ConstantMessage.MSG_ENTER_DATA,
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(UiFileTransfer.this,
                            ConstantMessage.MSG_SELECT_REPORT_TYPE,
                            ConstantMessage.MSG_SELECT_DATA,
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        threadCheck.start();

    }//GEN-LAST:event_btn_startUplaodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chose_file;
    private javax.swing.JButton btn_lookup_files;
    private javax.swing.JButton btn_startUplaod;
    private javax.swing.JComboBox comboReportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_files_server;
    private javax.swing.JTextField txt_location_file;
    private javax.swing.JTextArea txt_remark;
    private javax.swing.JTextField txt_stmp;
    // End of variables declaration//GEN-END:variables
}
