/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.component.HeaderRenderer;
import com.claim.controller.LogAppController;
import com.claim.object.ObjLogApplication;
import java.awt.event.ItemEvent;
import java.util.List;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poolsawat
 */
public class UiLogReport extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModel;

    /**
     * Creates new form UiHistoryVersion
     */
    public UiLogReport() {
        initComponents();
        tableModel = (DefaultTableModel) tableLogReport.getModel();
        loadCombobox();
        loadTable("");
    }

    private void loadCombobox() {
        List<String> listRpt = new LogAppController().getRptNameInLogReport();
        for (String listRpt1 : listRpt) {
            comboRptname.addItem(listRpt1);
        }
    }

    private void loadTable(String rptname) {
        ((DefaultTableModel) tableLogReport.getModel()).setRowCount(0);
        List<ObjLogApplication> listLog = new LogAppController().getListLogReport(rptname);
        for (int i = 0; i < listLog.size(); i++) {
            ObjLogApplication objLog = listLog.get(i);
            Vector data = new Vector();
            data.add(objLog.getLog_name());
            data.add(objLog.getStmp());
            data.add(objLog.getRecord());
            data.add(objLog.getResult());
            data.add(objLog.getLog_createdate());
            data.add(objLog.getLog_desc());
            tableModel.addRow(data);
            tableLogReport.setRowHeight(i, 30);
        }
        tableLogReport.setModel(tableModel);

        new HeaderRenderer().setWidthAsPercentages(tableLogReport, 0.22, 0.08, 0.05, 0.10, 0.15, 0.42);
        ((DefaultTableCellRenderer) tableLogReport.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLogReport = new javax.swing.JTable();
        comboRptname = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1300, 550));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "รายการข้อมูลผลการสร้างข้อมูลทั้งหมด", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("TH SarabunPSK", 1, 24))); // NOI18N

        tableLogReport.setAutoCreateRowSorter(true);
        tableLogReport.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        tableLogReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ชื่อรายงาน", "stmp", "record", "result", "วันที่ประมวลผล", "คำอธิบาย"
            }
        ));
        jScrollPane1.setViewportView(tableLogReport);

        comboRptname.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        comboRptname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- ทั้งหมด ----" }));
        comboRptname.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboRptnameItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        jLabel1.setText("รูปแบบรายงาน");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboRptname, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRptname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboRptnameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboRptnameItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (comboRptname.getSelectedIndex() == 0) {
                loadTable("");
            } else {
                String rpt_name = (String) comboRptname.getSelectedItem();
                loadTable(rpt_name);
            }
        }
    }//GEN-LAST:event_comboRptnameItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboRptname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLogReport;
    // End of variables declaration//GEN-END:variables
}
