/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.controller.Center16AndJula2015Controller;
import com.claim.controller.Center16AndJulaController;
import com.claim.controller.LogAppController;
import com.claim.dao.UtilDao;
import com.claim.object.HospitalService;
import com.claim.object.OppReport;
import com.claim.object.Stmp;
import com.claim.support.ArrayListUtil;
import com.claim.support.FunctionUtil;
import com.claim.constants.ConstantMessage;
import com.claim.support.DateUtil;
import com.claim.support.NetUtils;
import com.claim.object.ProgrameStatus;
import com.claim.dialog.DialogWaitProcess;
import com.claim.support.FileUtil;
import java.io.File;
import java.net.UnknownHostException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Poolsawat.a
 */
public class UiReportChula16 extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiReportChula16
     */
    public static int PROCESS = 0;
    Center16AndJulaController center16AndJulaController;
    List<HospitalService> listSelectHospital = null;
    List<Stmp> listStmpCenter16_jula = null;
    FunctionUtil baseFunction;
    static int MAX_MONTH_BUDGET = 9;

    public UiReportChula16() {
        initComponents();
        center16AndJulaController = new Center16AndJulaController();
        listSelectHospital = new ArrayList<HospitalService>();
        listStmpCenter16_jula = new ArrayList<Stmp>();
        baseFunction = new FunctionUtil();

        this.loadCombo();

        PROCESS = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rGroupCenterChulaCondition = new javax.swing.ButtonGroup();
        tab0_16_Jula = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        comboYearCenter16Jula = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        comboNumCenter16Jula = new javax.swing.JComboBox();
        jPanel40 = new javax.swing.JPanel();
        radioCondition16 = new javax.swing.JRadioButton();
        radioConditionJula = new javax.swing.JRadioButton();
        jPanel41 = new javax.swing.JPanel();
        btnCenter16JulaPathFile = new javax.swing.JButton();
        txtPathFileCenter16Jula = new javax.swing.JTextField();
        btnCenter16JulaPathFileDesktop1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCenter16JularGenReport = new javax.swing.JButton();
        btnCenter16JularGenReportAll = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("หน้าจอออกรายงาน Chula16");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Excel-icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 550));

        jPanel38.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "งวดการจ่ายเงิน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel28.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel28.setText("ปีเดือน");

        comboYearCenter16Jula.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        comboYearCenter16Jula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboYearCenter16JulaItemStateChanged(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel29.setText("งวดที่");

        comboNumCenter16Jula.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        comboNumCenter16Jula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNumCenter16JulaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboYearCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNumCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(comboNumCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(comboYearCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel40.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "เงื่อนไขที่ออก", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        rGroupCenterChulaCondition.add(radioCondition16);
        radioCondition16.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radioCondition16.setText("ศุนย์ 16");

        rGroupCenterChulaCondition.add(radioConditionJula);
        radioConditionJula.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        radioConditionJula.setText("รพ. จุฬา");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(radioCondition16)
                .addGap(48, 48, 48)
                .addComponent(radioConditionJula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioConditionJula)
                    .addComponent(radioCondition16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel41.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "สถานที่เก็บไฟล์", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        btnCenter16JulaPathFile.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btnCenter16JulaPathFile.setText("เลือก");
        btnCenter16JulaPathFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenter16JulaPathFileActionPerformed(evt);
            }
        });

        txtPathFileCenter16Jula.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txtPathFileCenter16Jula.setEnabled(false);

        btnCenter16JulaPathFileDesktop1.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btnCenter16JulaPathFileDesktop1.setText("desktop");
        btnCenter16JulaPathFileDesktop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenter16JulaPathFileDesktop1jButtonFolderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCenter16JulaPathFileDesktop1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCenter16JulaPathFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPathFileCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCenter16JulaPathFile)
                    .addComponent(txtPathFileCenter16Jula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCenter16JulaPathFileDesktop1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tab0_16_JulaLayout = new javax.swing.GroupLayout(tab0_16_Jula);
        tab0_16_Jula.setLayout(tab0_16_JulaLayout);
        tab0_16_JulaLayout.setHorizontalGroup(
            tab0_16_JulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab0_16_JulaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab0_16_JulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, 862, Short.MAX_VALUE)
                    .addComponent(jPanel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab0_16_JulaLayout.setVerticalGroup(
            tab0_16_JulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab0_16_JulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "เครื่องมือการออกรายงาน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(215, 445));

        btnCenter16JularGenReport.setBackground(new java.awt.Color(153, 153, 255));
        btnCenter16JularGenReport.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btnCenter16JularGenReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Print-icon.png"))); // NOI18N
        btnCenter16JularGenReport.setText("ออกรายงาน");
        btnCenter16JularGenReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenter16JularGenReportActionPerformed(evt);
            }
        });

        btnCenter16JularGenReportAll.setBackground(new java.awt.Color(255, 204, 0));
        btnCenter16JularGenReportAll.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        btnCenter16JularGenReportAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Print-icon.png"))); // NOI18N
        btnCenter16JularGenReportAll.setText("ออกรายงาน ทุกอย่าง");
        btnCenter16JularGenReportAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCenter16JularGenReportAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCenter16JularGenReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCenter16JularGenReportAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnCenter16JularGenReport, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnCenter16JularGenReportAll, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab0_16_Jula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tab0_16_Jula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboYearCenter16JulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboYearCenter16JulaItemStateChanged
        comboNumCenter16Jula.removeAllItems();
        comboNumCenter16Jula.addItem("-");
        for (Stmp stmp : listStmpCenter16_jula) {
            //System.out.println("comboYearOpaeIndv.getSelectedItem()++"+comboYearOpaeIndv.getSelectedItem());
            //System.out.println("stmp.getStmpYM()++"+stmp.getStmpYM());
            if (comboYearCenter16Jula.getSelectedItem().equals(stmp.getStmpYM())
                    && comboNumCenter16Jula.getSelectedItem() != stmp.getStmpN()) {
                comboNumCenter16Jula.addItem(stmp.getStmpN());
            }
        }
    }//GEN-LAST:event_comboYearCenter16JulaItemStateChanged

    private void comboNumCenter16JulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNumCenter16JulaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNumCenter16JulaItemStateChanged

    private void btnCenter16JulaPathFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenter16JulaPathFileActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogTitle("Open Folder");
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setCurrentDirectory(new File(""));
            int result = fc.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                File a = fc.getSelectedFile();
                // Path File method in this class
                String temp = a.getPath();
                txtPathFileCenter16Jula.setText(".");

                if (temp != null) {
                    txtPathFileCenter16Jula.setText(temp);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCenter16JulaPathFileActionPerformed

    private void btnCenter16JulaPathFileDesktop1jButtonFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenter16JulaPathFileDesktop1jButtonFolderActionPerformed
        txtPathFileCenter16Jula.setText(FileUtil.getPathDesktop());
    }//GEN-LAST:event_btnCenter16JulaPathFileDesktop1jButtonFolderActionPerformed

    private void btnCenter16JularGenReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenter16JularGenReportActionPerformed
        final DialogWaitProcess waitArea = new DialogWaitProcess();
        try {
            if (comboYearCenter16Jula.getSelectedIndex() != 0) {
                if (comboNumCenter16Jula.getSelectedIndex() != 0) {
                    if (radioCondition16.isSelected() || radioConditionJula.isSelected()) {
                        if (!txtPathFileCenter16Jula.getText().isEmpty()) {
                            int selectOption = JOptionPane.showConfirmDialog(null,
                                    ConstantMessage.MSG_REPORT_CONFIRM,
                                    ConstantMessage.MSG_REPORT_INFOMATION, JOptionPane.YES_NO_OPTION);
                            if (selectOption == JOptionPane.YES_OPTION) {
                                waitArea.setVisible(true);
                                Thread thread = new Thread(new Runnable() {
                                    @Override
                                    public void run() {
                                        DateUtil dateUtil = new DateUtil();
                                        ProgrameStatus programeStatus = new ProgrameStatus();
                                        try {
                                            OppReport report = setInputFormReport();
                                            waitArea.setTitle(ConstantMessage.MSG_PROGRAME_PROCESSSING);
                                            boolean is2015 = dateUtil.checkStmpBudgetYear2015(report.getStmp(), MAX_MONTH_BUDGET);
                                            if (is2015) {
                                                programeStatus = new Center16AndJula2015Controller().center16_Jula_2015(report);
                                            } else {
                                                programeStatus = center16AndJulaController.center16_Jula(report);
                                            }
                                            waitArea.setVisible(false);
                                            baseFunction.openDirectoryAutomatic(report.getPathFile());
                                            /*
                                            * 17-08-2015
                                            */
                                            /*try {                                                
                                                new LogAppController().createLog("ทำการออกรายงาน", "ทำการออกรายงาน ศูนย์ 16 จุฬา ", NetUtils.getIpAddress(), 1);
                                            } catch (UnknownHostException ex) {
                                                Logger.getLogger(UiMainClaim.class.getName()).log(Level.SEVERE, null, ex);
                                            }*/
                                        } catch (Exception e) {
                                            e.printStackTrace();
                                        }
                                    }
                                });
                                thread.start();
                            }
                        } else {
                            JOptionPane.showMessageDialog(this,
                                    ConstantMessage.MSG_FILE_LOCATION_PLEASE,
                                    ConstantMessage.MSG_FILE_LOCATION,
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                                "กรุณาเลือก เงื่อนไขที่ออก",
                                ConstantMessage.MSG_SELECT_DATA,
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "กรุณาเลือกงวดที่",
                            ConstantMessage.MSG_SELECT_DATA,
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        ConstantMessage.MSG_SELECT_DATE_PLEASE,
                        ConstantMessage.MSG_SELECT_DATA,
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCenter16JularGenReportActionPerformed

    private void btnCenter16JularGenReportAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCenter16JularGenReportAllActionPerformed
        final DialogWaitProcess waitArea = new DialogWaitProcess();
        try {
            if (comboYearCenter16Jula.getSelectedIndex() != 0) {
                if (comboNumCenter16Jula.getSelectedIndex() != 0) {
                    if (!txtPathFileCenter16Jula.getText().isEmpty()) {
                        int selectOption = JOptionPane.showConfirmDialog(null,
                                ConstantMessage.MSG_REPORT_CONFIRM,
                                ConstantMessage.MSG_REPORT_INFOMATION, JOptionPane.YES_NO_OPTION);
                        if (selectOption == JOptionPane.YES_OPTION) {
                            waitArea.setVisible(true);
                            Thread thread = new Thread(new Runnable() {
                                @Override
                                public void run() {
                                    ProgrameStatus programeStatus = new ProgrameStatus();
                                    try {
                                        OppReport report = setInputFormReport();
                                        waitArea.setTitle(ConstantMessage.MSG_PROGRAME_PROCESSSING);
                                        boolean is2015 = new DateUtil().checkStmpBudgetYear2015(report.getStmp(), MAX_MONTH_BUDGET);
                                        if (is2015) {
                                            programeStatus = new Center16AndJula2015Controller().center16_Jula_All(report);
                                        } else {
                                            programeStatus = center16AndJulaController.center16_Jula_All(report);
                                        }
                                        waitArea.setVisible(false);
                                        baseFunction.openDirectoryAutomatic(report.getPathFile());
                                    } catch (Exception e) {
                                        e.printStackTrace();
                                    }
                                }
                            });
                            thread.start();
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                                ConstantMessage.MSG_FILE_LOCATION_PLEASE,
                                ConstantMessage.MSG_FILE_LOCATION,
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                            "กรุณาเลือกงวดที่",
                            ConstantMessage.MSG_SELECT_DATA,
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        ConstantMessage.MSG_SELECT_DATE_PLEASE,
                        ConstantMessage.MSG_SELECT_DATA,
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCenter16JularGenReportAllActionPerformed
    public void loadCombo() {
        try {
            //Tab Center 16 _jula
            //get Stmp From Table RPT_OPBKK_HC16CHULA
            comboYearCenter16Jula.removeAllItems();
            comboYearCenter16Jula.addItem("-");
            listStmpCenter16_jula = new UtilDao().getStmpDistinct("RPT_OPBKK_HC16CHULA", "STMP");

            List<String> listCenter16_jula = new ArrayList<String>();

            for (int i = 0; i < listStmpCenter16_jula.size(); i++) {
                listCenter16_jula.add(listStmpCenter16_jula.get(i).getStmpYM());
            }
            List<String> listUnDup =  ArrayListUtil.removeDuplicates(listCenter16_jula);            
            Collections.sort(listUnDup);
            for (String string : listUnDup) {
                comboYearCenter16Jula.addItem(string);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public OppReport setInputFormReport() {
        OppReport report = new OppReport();
        report.setYearMonth(comboYearCenter16Jula.getSelectedItem().toString());
        report.setNo(comboNumCenter16Jula.getSelectedItem().toString());
        report.setPathFile(txtPathFileCenter16Jula.getText());
        report.setMonth(baseFunction.subStringYearMonth(comboYearCenter16Jula.getSelectedItem().toString()).get("M").toString());
        report.setYear(baseFunction.subStringYearMonth(comboYearCenter16Jula.getSelectedItem().toString()).get("Y").toString());
        report.setStmp(report.getYear() + report.getMonth() + "-" + report.getNo());
        if (radioCondition16.isSelected()) {
            report.setServiceCode("13661");
        } else if (radioConditionJula.isSelected()) {
            report.setServiceCode("13756");
        }
        return report;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCenter16JulaPathFile;
    private javax.swing.JButton btnCenter16JulaPathFileDesktop1;
    private javax.swing.JButton btnCenter16JularGenReport;
    private javax.swing.JButton btnCenter16JularGenReportAll;
    private javax.swing.JComboBox comboNumCenter16Jula;
    private javax.swing.JComboBox comboYearCenter16Jula;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.ButtonGroup rGroupCenterChulaCondition;
    private javax.swing.JRadioButton radioCondition16;
    private javax.swing.JRadioButton radioConditionJula;
    private javax.swing.JPanel tab0_16_Jula;
    private javax.swing.JTextField txtPathFileCenter16Jula;
    // End of variables declaration//GEN-END:variables
}
