/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.claim.ui;

import com.claim.controller.InitProgramController;
import com.claim.object.ObjProgramVersion;
import com.claim.config.ConfigApp;
import com.claim.support.NetUtils;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Poolsawat.a
 */
public class UiAboutPrograme extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiAboutPrograme
     */
    public UiAboutPrograme() {
        initComponents();
        txt_program_version.setText(ConfigApp.VERSION_APP);
        if (NetUtils.getIpAddress().equals(ConfigApp.IP_DEV)) {
            btnUpVersion.setEnabled(true);
        } else {
            btnUpVersion.setEnabled(false);
        }
        ObjProgramVersion objVesion = new InitProgramController().getLatVersionProgram(ConfigApp.VERSION_APP);
        lb_lastupdate.setText("วันที่แก้ไขโปรแกรมล่าสุด " + objVesion.getVersion_updatedate());
        txt_version_desc.append(objVesion.getVersion_desc());
    }

    public static void main(String[] args) {
        System.out.println(" load application ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel44 = new javax.swing.JPanel();
        lb_lastupdate = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txt_version_desc = new javax.swing.JTextArea();
        txt_program_version = new javax.swing.JTextField();
        btnUpVersion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/claim/util/images/Excel-icon.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 550));

        jPanel44.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "เกี่ยวกับโปรแกรม", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lb_lastupdate.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        lb_lastupdate.setText("แกไข ล่าสุด เมื่อ วันที่ 24-09-2557  17.00");

        jLabel36.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel36.setText("พัฒนาโดย พูลสวัสดิ์ อภิญ (พูล)");

        jLabel37.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel37.setText("โปรแกรมเกิดปัญหา กรุณา ติดต่อ พูล หรือ แผนก IT ตลอดเวลาทำการ 09.00 - 16.30 ");

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_lastupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_lastupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addContainerGap())
        );

        jPanel47.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ปรับปรุงแก้ไข", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel42.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel42.setText("เวอชั่น ");

        txt_version_desc.setBackground(new java.awt.Color(254, 235, 235));
        txt_version_desc.setColumns(20);
        txt_version_desc.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        txt_version_desc.setForeground(new java.awt.Color(51, 102, 255));
        txt_version_desc.setLineWrap(true);
        txt_version_desc.setRows(5);
        jScrollPane15.setViewportView(txt_version_desc);

        txt_program_version.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        txt_program_version.setText("1.3.2");
        txt_program_version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_program_versionActionPerformed(evt);
            }
        });

        btnUpVersion.setFont(new java.awt.Font("TH SarabunPSK", 1, 20)); // NOI18N
        btnUpVersion.setText("อัพเดทเวอชั่น");
        btnUpVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpVersionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("*** กรุณาไป อัพเดท เวอชั่นที่ ConfigApp.java ด้วย ก่อนการอัพเดท เวอชั่น เข้า ฐานข้อมูล");

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel47Layout.createSequentialGroup()
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_program_version, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel47Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txt_program_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpVersion)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpVersionActionPerformed
        InitProgramController initController = new InitProgramController();
        int selectOption = JOptionPane.showConfirmDialog(null,
                "ยืนยันการ อัพเดทเวอชั่นโปรแกรม",
                "ยืนยัน", JOptionPane.YES_NO_OPTION);
        if (selectOption == JOptionPane.YES_OPTION) {
            ObjProgramVersion obj = new ObjProgramVersion();
            obj.setVersion_desc(txt_version_desc.getText().trim());
            obj.setVersion_updateby("poolsawat");
            obj.setVersion_name(txt_program_version.getText().trim());
            int exec = initController.updateVersionProgram(obj);
            String title_jpanel = "หน้าจอตรวจสอบเวอชั่นของโปรแกรม";
            if (exec == 1) {
                JOptionPane.showMessageDialog(UiAboutPrograme.this,
                        "อัพเดทเวอชั่นของโปรแกรม ได้ถูกอัพเดทใหม่แล้ว",
                        title_jpanel,
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(UiAboutPrograme.this,
                        "โอัพเดทเวอชั่นของโปรแกรม เกิดข้อผิดพลาด",
                        title_jpanel,
                        JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpVersionActionPerformed

    private void txt_program_versionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_program_versionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_program_versionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JLabel lb_lastupdate;
    public static javax.swing.JTextField txt_program_version;
    private javax.swing.JTextArea txt_version_desc;
    // End of variables declaration//GEN-END:variables
}
